sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.8.1

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - docker volume create --name=postgres-db-volume
  - docker volume create --name=es-data
  - docker volume create --name=jupyter-work
  - docker volume create --name=es-backup-201707
  - docker-compose up -d
  - docker-compose ps
  - sleep 30s
  - if [[ $(docker ps --format '{{.Names}}' | grep db) != 'db' ]]; then exit 1; fi
  - sleep 30s
  - if [[ $(docker ps --format '{{.Names}}' | grep elastic) != 'elastic' ]]; then exit 1; fi
  - sleep 30s
  - if [[ $(docker ps --format '{{.Names}}' | grep oscapi) != 'oscapi' ]]; then exit 1; fi
  - sleep 30s
  - if [[ $(docker ps --format '{{.Names}}' | grep oscweb) != 'oscweb' ]]; then exit 1; fi
  - if [[ $(docker ps --format '{{.Names}}' | grep kibana) != 'kibana' ]]; then exit 1; fi
  - sleep 30s
  - if [[ $(docker ps --format '{{.Names}}' | grep letsencrytp) != 'letsencrytp' ]]; then exit 1; fi
  - if [[ $(docker ps --format '{{.Names}}' | grep nginx) != 'nginx' ]]; then exit 1; fi
  - sleep 30s
  - docker-compose scale oscweb=3
  - if [[ $(docker ps --format '{{.Names}}' | grep osc_web_2) != 'osc_oscweb_2' ]]; then exit 1; fi
  - if [[ $(docker ps --format '{{.Names}}' | grep osc_web_3) != 'osc_oscweb_3' ]]; then exit 1; fi


notifications:
  email: false
  slack:
    rooms:
    - opensmartcountry:gjRfTD0YvySQZPrFw1gFfGmk
    on_success: always
    on_failure: always
